### ISSUE TITLE
syntax error in chempy.kinetics.ode

### ISSUE THREAD

**Issue by souptonuts** [bjodah/chempy#105]
I installed chempy to my debian linux system using 
`$ python -m pip install --user --upgrade chempy pytest`

Installation seems successful

> Successfully installed MarkupSafe-1.0 Send2Trash-1.5.0 atomicwrites-1.2.1 attrs-18.2.0 backports-abc-0.5 backports.functools-lru-cache-1.5 backports.shutil-get-terminal-size-1.0.0 bleach-2.1.4 chempy-0.7.1 configparser-3.5.0 cycler-0.10.0 defusedxml-0.5.0 entrypoints-0.2.3 funcsigs-1.0.2 functools32-3.2.3.post2 futures-3.2.0 html5lib-1.0.1 ipykernel-4.9.0 ipython-5.8.0 ipython-genutils-0.2.0 ipywidgets-7.4.2 jinja2-2.10 jsonschema-2.6.0 jupyter-1.0.0 jupyter-client-5.2.3 jupyter-console-5.2.0 jupyter-core-4.4.0 kiwisolver-1.0.1 matplotlib-2.2.3 mistune-0.8.3 more-itertools-4.3.0 mpmath-1.0.0 nbconvert-5.4.0 nbformat-4.4.0 notebook-5.6.0 pandocfilters-1.4.2 pathlib2-2.3.2 pexpect-4.6.0 pickleshare-0.7.4 pluggy-0.7.1 prometheus-client-0.3.1 prompt-toolkit-1.0.15 ptyprocess-0.6.0 pulp-1.6.8 py-1.6.0 pygments-2.2.0 pyneqsys-0.5.4 pyodesys-0.12.3 pyparsing-2.2.0 pytest-3.8.0 pytz-2018.5 pyzmq-17.1.2 qtconsole-4.4.1 quantities-0.12.2 scandir-1.9.0 scipy-1.1.0 simplegeneric-0.8.1 singledispatch-3.4.0.3 subprocess32-3.5.2 sym-0.3.4 sympy-1.3 terminado-0.8.1 testpath-0.3.1 tornado-5.1 traitlets-4.3.2 wcwidth-0.1.7 webencodings-0.5.1 widgetsnbextension-3.4.2

I tried to run the chemical kinetics demo script found here []https://pypi.org/project/chempy/(url) using commandline:

`$ python
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from chempy import ReactionSystem  # The rate constants below are arbitrary
>>> rsys = ReactionSystem.from_string("""2 Fe+2 + H2O2 -> 2 Fe+3 + 2 OH-; 42
... 2 Fe+3 + H2O2 -> 2 Fe+2 + O2 + 2 H+; 17
... H+ + OH- -> H2O; 1e10
... H2O -> H+ + OH-; 1e-4""")  # "[H2O]" = 1.0 (actually 55.4 at RT)
>>> from chempy.kinetics.ode import get_odesys
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bob/.local/lib/python2.7/site-packages/chempy/kinetics/ode.py", line 556
    validate(dict(**c, **p))
                     ^
SyntaxError: invalid syntax
`

**Comment by souptonuts** [comment]
Thanks for the help.  I built with python3 and got no errors. I recreated
the chemical kinetics figure on the pypi documentation page.
It looks great and I can't wait to try it out.

**Comment by bjodah** [comment]
Great, what I've done now is:

- released v0.6.10 with Python 2 support, added a note to the README that Python 2 is deprecated in ChemPy 0.7 going onwards (and how to stay at 0.6.x)
- released v0.7.2 with Python 2 support, but 0.7.2 and onwards will emit a DeprecationWarning that `chempy<0.7` should be used if one wants to keep using python <3.5.

I'll keep backporting bugfixes to chempy-0.6.x so there will be no need to rush to Python 3.
