### ISSUE TITLE
Chempy install errors using pip

### ISSUE THREAD

**Issue by physicsnerd** [bjodah/chempy#51]
`pip install chempy` does not work out of the box on my Ubuntu system because compilation from source requires a few system packages that I didn't have. It would be nice to either distribute pre-compiled binaries for common systems, or to at least document which system packages are required. Even though the packages I needed were common (python-devel and gfortran), many new users get tripped up by this sort of thing.

**Comment by bjodah** [comment]
@physicsnerd thanks for the report. I'll look into providing binary wheels, currently the only binaries I provide are in the form of conda packages.

I'll try to update the README in the meantime.

**Comment by bjodah** [comment]
So I installed a fresh image of Ubuntu 16.04 in VirtualBox:
```
$ sudo apt install python-pip
$ pip install --user chempy
...
Successfully installed chempy ...
```
So everything worked fine for me.

`gfortran` shouldn't be needed, not sure about `python-dev` (but it was installed as a dependency for `python-pip`)

If you install `chempy[all]` there a large number of libraries needed (and they are a bit of a moving target), but then the `conda` package manager is really helpful.

**Comment by joeweaver** [comment]
On the off chance this helps, are you using the default pip version which shipped with Python 3.4?

I've had similar issues trying to install system packages with that version which went away once I upgraded pip.

**Comment by physicsnerd** [comment]
Adding these packages still gave an error - you also need the laplack blas packages, apparently.

**Comment by bjodah** [comment]
@physicsnerd what version of pip are you using (use `pip --version`), wheel support was added in 6 I think. If it's less than 9 I would do `pip --upgrade pip` (possibly with the `--user` flag if you haven't got root permissions)

**Comment by bjodah** [comment]
There is now a [Dockerfile](https://github.com/bjodah/chempy/blob/master/scripts/environment/Dockerfile) in the repo showing exactly what packages are needed.

The Dockerfile can be used to e.g. host jupyter notebooks (see the updated README)

**Comment by bjodah** [comment]
Closing this for now, feel free to re-open if installing is still an issue.
