### ISSUE TITLE
Conda install instructions don't work on macOS

### ISSUE THREAD

**Issue by bryanwweber** [bjodah/chempy#80]
Hi! This is related to openjournals/joss-reviews#565

The conda installation instructions don't work for me on macOS (although they do on Ubuntu). The error I receive is

```bash
$ conda create -n chempy -c bjodah chempy pytest
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - chempy
  - pyneqsys[version='>=0.5.1']
  - sym[version='>=0.3.1']
  - chempy
  - pyodesys[version='>=0.11.6']

Current channels:

  - https://conda.anaconda.org/bjodah/osx-64
  - https://conda.anaconda.org/bjodah/noarch
  - https://repo.continuum.io/pkgs/main/osx-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
```

You should list in the documentation/README which platforms are supported.

**Comment by bjodah** [comment]
So I've spent some time trying to build conda packages for all the major platforms. It was harder than I anticipated but os x should be doable in the forseeable future (e.g. [working on it here](https://github.com/conda-forge/staged-recipes/pull/5110)). But until then I've updated the README to state that Linux is the officially supported platform.

**Comment by bryanwweber** [comment]
OK this sounds good. Feel free to close if you want.
