### ISSUE TITLE
Required and optional dependencies should be clarified in the documentation

### ISSUE THREAD

**Issue by bryanwweber** [bjodah/chempy#81]
This is related to openjournals/joss-reviews#565

Although the dependencies are documented in `setup.py`, the purpose of all of them is not very clear, and the format may not be familiar to users who have not seen a `setup.py` file before. The dependencies and the features they enable should be clarified in the documentation.

**Comment by bjodah** [comment]
I tried to elaborate on this [here](https://github.com/bjodah/chempy/commit/5d1e70754a25e1f1cfd1cb6a790b2887d4fc3d04), what do you think, is it too terse? I can of course be more detailed.

**Comment by bryanwweber** [comment]
This seems fine to me!
