### ISSUE TITLE
examples/demo_kinetics.py throws TypeError

### ISSUE THREAD

**Issue by bryanwweber** [bjodah/chempy#88]
This is related to the review: https://github.com/openjournals/joss-reviews/issues/565

In trying to verify the functionality of the code, I ran into an error running examples/demo_kinetics.py. Running on Ubuntu 16.04, I installed ChemPy 0.6.5 from conda in a Python 3.6 environment, then cloned this repository, then

```bash
cd examples
python demo_kinetics.py
```

which results in

```python
Traceback (most recent call last):
  File "demo_kinetics.py", line 37, in <module>
    import argh
ModuleNotFoundError: No module named 'argh'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo_kinetics.py", line 39, in <module>
    main()
  File "demo_kinetics.py", line 25, in main
    expr = f(*args, **kwargs)
TypeError: pseudo_irrev() got an unexpected keyword argument 'exp'
```

**Comment by bjodah** [comment]
Thanks, fixed in gh-89. (argh wansn't even used so I dropped to import)
